
services:
  mordorwide-stunrelay:
    build:
      context: .
    image: mordorwide/stunrelay:latest
    container_name: mordorwide-stunrelay
    environment:
      - "CMD_HOST=${CMD_HOST}"
      - "CMD_PORT=${CMD_PORT}"
    ports:
      - "127.0.0.1:8080:8080"
